FROM mariadb:latest

# Copia el script SQL para la creación de la base de datos y el usuario. En este archivo esta la estructura de la base y los grants
COPY usuarios_db.sql /docker-entrypoint-initdb.d/

# Copiar los archivos de certificado al contenedor
COPY certs/mariadb-certs/private_key.pem /etc/mysql/private_key.pem
COPY certs/mariadb-certs/cert.csr /etc/mysql/cert.csr
COPY certs/mariadb-certs/cert.crt /etc/mysql/cert.crt

RUN chown -R mysql:mysql /etc/mysql/
# En my.cnf agregue la configuración de SSL
COPY ./my.cnf /etc/mysql/my.cnf

# Establecer la variable de entorno para inicializar la base de datos
ENV MYSQL_ROOT_PASSWORD=root
